### ISSUE TITLE
Custom Exceptions

### ISSUE THREAD

**Issue by RedBullDogE** [future-stardust/url-shrtnr-guitarosexuals#26]
I think we can add custom exceptions, as it suggested earlier by @IINamelessII, like UserNotFound, InvalidToken etc. It can make code more readable

**Comment by yugisu** [comment]
@IINamelessII I suppose we need a `UniqueRestrictionViolation` exception or something similar for Database.create and DatabaseTable prepare methods to replace `IllegalArgumentException`.

**Comment by IINamelessII** [comment]
@yugisu agree
